In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/Day8_Ecommerce_Sales_Dataset.csv")

df.head()

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI

In [3]:
print("Shape of dataset:", df.shape)

print("Columns:")
print(df.columns.tolist())

print("Data Types:")
print(df.dtypes)

Shape of dataset: (100, 13)
Columns:
['Order_ID', 'Order_Date', 'Customer', 'City', 'Region', 'Category', 'Product', 'Quantity', 'Unit_Price', 'Discount_Percent', 'Total_Sales', 'Rating', 'Payment_Method']
Data Types:
Order_ID              int64
Order_Date           object
Customer             object
City                 object
Region               object
Category             object
Product              object
Quantity              int64
Unit_Price            int64
Discount_Percent      int64
Total_Sales         float64
Rating              float64
Payment_Method       object
dtype: object

In [4]:
df.info()
df.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          100 non-null    int64
 1   Order_Date        100 non-null    object
 2   Customer          100 non-null    object
 3   City              100 non-null    object
 4   Region            100 non-null    object
 5   Category          100 non-null    object
 6   Product           100 non-null    object
 7   Quantity          100 non-null    int64
 8   Unit_Price        100 non-null    int64
 9   Discount_Percent  100 non-null    int64
 10  Total_Sales       100 non-null    float64
 11  Rating            100 non-null    float64
 12  Payment_Method    100 non-null    object
dtypes: float64(2), int64(4), object(7)
memory usage: 10.3+ KB

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
count,100.000000,100,100,100,100,100,100,100.000000,100.000000,100.000000,100.000000,100.000000,100
unique,NaN,78,25,15,4,5,23,NaN,NaN,NaN,NaN,NaN,5
top,NaN,2026-03-13,Aditya Verma,Chennai,North,Sports,Wireless Headphones,NaN,NaN,NaN,NaN,NaN,UPI
freq,NaN,3,9,10,38,25,7,NaN,NaN,NaN,NaN,NaN,26
mean,1050.500000,NaN,NaN,NaN,NaN,NaN,NaN,2.940000,1647.000000,6.500000,4472.629500,4.322000,NaN
std,29.011492,NaN,NaN,NaN,NaN,NaN,NaN,1.391315,970.054669,6.092718,3324.306691,0.414285,NaN
min,1001.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,499.000000,0.000000,449.100000,3.500000,NaN
25%,1025.750000,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,799.000000,0.000000,1948.050000,4.100000,NaN
50%,1050.500000,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,1499.000000,5.000000,3228.300000,4.300000,NaN
75%,1075.250000,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,2499.000000,11.250000,6427.562500,4.700000,NaN
max,1100.000000,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,3499.000000,15.000000,13995.000000,5.000000,NaN

In [5]:
#single column
df["Customer"]

0        Kabir Ali
1     Aditya Verma
2       Sara Ahmed
3        Kabir Ali
4      Priya Menon
          ...
95    Aditya Verma
96      Arjun Nair
97       Yusuf Dar
98     Hiba Sheikh
99       Kabir Ali
Name: Customer, Length: 100, dtype: object

In [6]:
#multiple columns
df[["Customer","City","Category"]]

        Customer       City        Category
0      Kabir Ali  Hyderabad     Electronics
1   Aditya Verma      Jammu          Sports
2     Sara Ahmed    Chennai     Electronics
3      Kabir Ali    Lucknow     Electronics
4    Priya Menon      Jammu     Electronics
..           ...        ...             ...
95  Aditya Verma      Kochi          Sports
96    Arjun Nair     Mumbai        Clothing
97     Yusuf Dar  Bengaluru  Home & Kitchen
98   Hiba Sheikh  Ahmedabad           Books
99     Kabir Ali       Pune           Books

[100 rows x 3 columns]

In [10]:
df.isna().sum()

Order_ID            0
Order_Date          0
Customer            0
City                0
Region              0
Category            0
Product             0
Quantity            0
Unit_Price          0
Discount_Percent    0
Total_Sales         0
Rating              0
Payment_Method      0
dtype: int64

In [11]:
#select specific columns and rows
df.loc[0:4, ["Order_ID", "Product", "Total_Sales"]]

   Order_ID              Product  Total_Sales
0      1001  Wireless Headphones      4497.00
1      1002        Running Shoes      2799.00
2      1003           Power Bank      2038.30
3      1004  Mechanical Keyboard      9496.20
4      1005          Smart Watch      3134.05

In [12]:
high_sales = df[df["Total_Sales"] > 5000]

high_sales

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
7,1008,2026-04-27,Aman Kumar,Jammu,North,Clothing,Hoodie,4,1599,5,6076.20,4.3,Credit Card
9,1010,2026-03-11,Aman Kumar,Kochi,South,Clothing,Jacket,4,2499,10,8996.40,4.7,Credit Card
10,1011,2026-03-22,Rahul Das,Hyderabad,South,Home & Kitchen,Coffee Maker,2,3499,0,6998.00,4.2,UPI
12,1013,2026-03-09,Maryam Khan,Lucknow,North,Clothing,Jacket,5,2499,15,10620.75,4.8,Net Banking
13,1014,2026-02-05,Dev Patel,Jaipur,North,Sports,Running Shoes,3,2799,0,8397.00,4.6,UPI
16,1017,2026-03-17,Sana Malik,Hyderabad,South,Sports,Cricket Bat,3,2499,0,7497.00,4.0,Net Banking
18,1019,2026-05-19,Reyansh Jain,Chennai,South,Clothing,Jacket,3,2499,0,7497.00,4.7,UPI
27,1028,2026-04-19,Sana Malik,Chandigarh,North,Electronics,Wireless Headphones,4,1499,5,5696.20,4.6,UPI
28,1029,2026-01-28,Sara Ahmed,Hyderabad,South,Electronics,Wireless Headphones,4,1499,5,5696.20,4.1,Credit Card
32,1033,2026-06-28,Maryam Khan,Pune,West,Home & Kitchen,Mixer Grinder,3,2999,10,8097.30,4.7,Net Banking
37,1038,2026-03-08,Aditya Verma,Pune,West,Sports,Dumbbell Set,5,1999,5,9495.25,5.0,Debit Card
38,1039,2026-04-28,Vivaan Kapoor,Chandigarh,North,Home & Kitchen,Mixer Grinder,2,2999,5,5698.10,3.8,UPI
40,1041,2026-03-14,Ishita Gupta,Delhi,North,Home & Kitchen,Coffee Maker,2,3499,5,6648.10,4.6,Cash on Delivery
47,1048,2026-06-24,Sara Ahmed,Lucknow,North,Home & Kitchen,Coffee Maker,3,3499,0,10497.00,5.0,UPI
48,1049,2026-03-02,Ishita Gupta,Mumbai,West,Sports,Running Shoes,5,2799,0,13995.00,4.0,Net Banking
50,1051,2026-04-28,Aisha Mir,Bhubaneswar,East,Electronics,Smart Watch,2,3299,0,6598.00,4.2,Credit Card
51,1052,2026-03-13,Rohan Mehta,Chandigarh,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.2,Debit Card
52,1053,2026-01-08,Ananya Singh,Hyderabad,South,Sports,Running Shoes,5,2799,5,13295.25,4.2,Credit Card
56,1057,2026-03-21,Alina Shah,Chennai,South,Home & Kitchen,Coffee Maker,3,3499,15,8922.45,4.5,Debit Card
58,1059,2026-01-01,Mehak Bhat,Chennai,South,Sports,Cricket Bat,4,2499,15,8496.60,4.2,Credit Card
59,1060,2026-04-24,Karan Joshi,Pune,West,Sports,Dumbbell Set,3,1999,10,5397.30,5.0,Credit Card
61,1062,2026-02-20,Kabir Ali,Mumbai,West,Electronics,Mechanical Keyboard,3,2499,0,7497.00,3.5,UPI
65,1066,2026-06-20,Dev Patel,Jaipur,North,Electronics,Smart Watch,2,3299,10,5938.20,4.7,Cash on Delivery
69,1070,2026-06-30,Aditya Verma,Delhi,North,Clothing,Jacket,4,2499,0,9996.00,3.8,Net Banking
75,1076,2026-04-29,Ishita Gupta,Chennai,South,Electronics,Wireless Headphones,4,1499,0,5996.00,3.5,Debit Card
76,1077,2026-03-28,Reyansh Jain,Pune,West,Home & Kitchen,Electric Kettle,4,1499,5,5696.20,4.5,Debit Card
79,1080,2026-05-25,Aditya Verma,Delhi,North,Clothing,Jacket,4,2499,0,9996.00,4.6,Debit Card
80,1081,2026-01-30,Reyansh Jain,Kolkata,East,Home & Kitchen,Electric Kettle,5,1499,15,6370.75,4.0,Debit Card
84,1085,2026-01-28,Sana Malik,Hyderabad,South,Home & Kitchen,Coffee Maker,4,3499,10,12596.40,4.3,Net Banking
89,1090,2026-05-13,Aditya Verma,Lucknow,North,Sports,Cricket Bat,5,2499,0,12495.00,3.8,Credit Card
92,1093,2026-05-16,Aisha Mir,Hyderabad,South,Sports,Cricket Bat,4,2499,15,8496.60,4.5,Cash on Delivery
93,1094,2026-03-06,Sara Ahmed,Mumbai,West,Home & Kitchen,Mixer Grinder,3,2999,5,8547.15,3.8,Credit Card
95,1096,2026-01-26,Aditya Verma,Kochi,South,Sports,Dumbbell Set,5,1999,5,9495.25,4.2,Credit Card
97,1098,2026-01-04,Yusuf Dar,Bengaluru,South,Home & Kitchen,Electric Kettle,4,1499,0,5996.00,4.2,Net Banking

In [13]:
df[df["Category"] == "Electronics"]

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI
14,1015,2026-06-24,Sana Malik,Kolkata,East,Electronics,Wireless Headphones,2,1499,0,2998.00,4.8,UPI
25,1026,2026-05-12,Sara Ahmed,Chandigarh,North,Electronics,Wireless Headphones,3,1499,0,4497.00,4.2,Net Banking
27,1028,2026-04-19,Sana Malik,Chandigarh,North,Electronics,Wireless Headphones,4,1499,5,5696.20,4.6,UPI
28,1029,2026-01-28,Sara Ahmed,Hyderabad,South,Electronics,Wireless Headphones,4,1499,5,5696.20,4.1,Credit Card
36,1037,2026-06-02,Zoya Khan,Pune,West,Electronics,Power Bank,2,1199,15,2038.30,4.8,UPI
46,1047,2026-02-07,Sana Malik,Bengaluru,South,Electronics,Wireless Mouse,5,899,15,3820.75,4.0,UPI
50,1051,2026-04-28,Aisha Mir,Bhubaneswar,East,Electronics,Smart Watch,2,3299,0,6598.00,4.2,Credit Card
51,1052,2026-03-13,Rohan Mehta,Chandigarh,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.2,Debit Card
61,1062,2026-02-20,Kabir Ali,Mumbai,West,Electronics,Mechanical Keyboard,3,2499,0,7497.00,3.5,UPI
65,1066,2026-06-20,Dev Patel,Jaipur,North,Electronics,Smart Watch,2,3299,10,5938.20,4.7,Cash on Delivery
68,1069,2026-03-27,Vivaan Kapoor,Ahmedabad,West,Electronics,Wireless Mouse,2,899,5,1708.10,4.7,UPI
75,1076,2026-04-29,Ishita Gupta,Chennai,South,Electronics,Wireless Headphones,4,1499,0,5996.00,3.5,Debit Card
83,1084,2026-06-19,Aisha Mir,Kolkata,East,Electronics,Wireless Mouse,5,899,10,4045.50,3.8,Cash on Delivery
91,1092,2026-04-14,Nikhil Sood,Ahmedabad,West,Electronics,Wireless Headphones,3,1499,0,4497.00,4.1,Debit Card
94,1095,2026-02-25,Maryam Khan,Mumbai,West,Electronics,Power Bank,2,1199,0,2398.00,4.6,Debit Card

In [14]:
df.sort_values(by="Total_Sales", ascending=False)

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
48,1049,2026-03-02,Ishita Gupta,Mumbai,West,Sports,Running Shoes,5,2799,0,13995.00,4.0,Net Banking
52,1053,2026-01-08,Ananya Singh,Hyderabad,South,Sports,Running Shoes,5,2799,5,13295.25,4.2,Credit Card
84,1085,2026-01-28,Sana Malik,Hyderabad,South,Home & Kitchen,Coffee Maker,4,3499,10,12596.40,4.3,Net Banking
89,1090,2026-05-13,Aditya Verma,Lucknow,North,Sports,Cricket Bat,5,2499,0,12495.00,3.8,Credit Card
12,1013,2026-03-09,Maryam Khan,Lucknow,North,Clothing,Jacket,5,2499,15,10620.75,4.8,Net Banking
...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,1061,2026-05-12,Alina Shah,Bengaluru,South,Books,Python Programming,1,749,5,711.55,5.0,Cash on Delivery
96,1097,2026-02-02,Arjun Nair,Mumbai,West,Clothing,T-Shirt,1,799,15,679.15,3.5,UPI
73,1074,2026-03-28,Alina Shah,Lucknow,North,Books,Atomic Habits,1,599,10,539.10,5.0,Net Banking
5,1006,2026-01-21,Manya Rao,Kochi,South,Books,The Alchemist,1,499,10,449.10,4.2,Cash on Delivery
62,1063,2026-04-17,Aman Kumar,Chandigarh,North,Books,The Alchemist,1,499,10,449.10,4.8,Credit Card

In [15]:
df.sort_values(by="Total_Sales", ascending=False)

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
48,1049,2026-03-02,Ishita Gupta,Mumbai,West,Sports,Running Shoes,5,2799,0,13995.00,4.0,Net Banking
52,1053,2026-01-08,Ananya Singh,Hyderabad,South,Sports,Running Shoes,5,2799,5,13295.25,4.2,Credit Card
84,1085,2026-01-28,Sana Malik,Hyderabad,South,Home & Kitchen,Coffee Maker,4,3499,10,12596.40,4.3,Net Banking
89,1090,2026-05-13,Aditya Verma,Lucknow,North,Sports,Cricket Bat,5,2499,0,12495.00,3.8,Credit Card
12,1013,2026-03-09,Maryam Khan,Lucknow,North,Clothing,Jacket,5,2499,15,10620.75,4.8,Net Banking
...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,1061,2026-05-12,Alina Shah,Bengaluru,South,Books,Python Programming,1,749,5,711.55,5.0,Cash on Delivery
96,1097,2026-02-02,Arjun Nair,Mumbai,West,Clothing,T-Shirt,1,799,15,679.15,3.5,UPI
73,1074,2026-03-28,Alina Shah,Lucknow,North,Books,Atomic Habits,1,599,10,539.10,5.0,Net Banking
5,1006,2026-01-21,Manya Rao,Kochi,South,Books,The Alchemist,1,499,10,449.10,4.2,Cash on Delivery
62,1063,2026-04-17,Aman Kumar,Chandigarh,North,Books,The Alchemist,1,499,10,449.10,4.8,Credit Card

In [16]:
total_sales = df["Total_Sales"].sum()

print("Total Sales:", total_sales)

Total Sales: 447262.95000000007

In [18]:
average_sales = df["Total_Sales"].mean()

print("Average Sales:", average_sales)

Average Sales: 4472.629500000001

In [19]:
total_quantity = df["Quantity"].sum()

print("Total Quantity Sold:", total_quantity)

Total Quantity Sold: 294

In [20]:
category_sales = (
    df.groupby("Category")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

category_sales

Category
Sports            136026.45
Home & Kitchen    113329.90
Electronics        92086.00
Clothing           69028.20
Books              36792.40
Name: Total_Sales, dtype: float64

In [21]:
category_average = (
    df.groupby("Category")["Total_Sales"]
    .mean()
    .sort_values(ascending=False)
)

category_average

Category
Sports            5441.058000
Home & Kitchen    5396.661905
Clothing          4930.585714
Electronics       4846.631579
Books             1752.019048
Name: Total_Sales, dtype: float64

In [22]:
city_sales = (
    df.groupby("City")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

city_sales

City
Hyderabad      59076.45
Chennai        47493.20
Lucknow        46194.65
Pune           41908.55
Mumbai         41457.80
Kochi          37257.50
Chandigarh     34539.65
Delhi          30882.80
Jaipur         25534.00
Kolkata        20169.00
Jammu          16059.75
Ahmedabad      14788.70
Bengaluru      13524.30
Srinagar       11778.60
Bhubaneswar     6598.00
Name: Total_Sales, dtype: float64

In [23]:
city_sales.head(5)

City
Hyderabad    59076.45
Chennai      47493.20
Lucknow      46194.65
Pune         41908.55
Mumbai       41457.80
Name: Total_Sales, dtype: float64

In [24]:
product_sales = (
    df.groupby("Product")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

product_sales

Product
Coffee Maker               51610.25
Jacket                     47106.15
Cricket Bat                41483.40
Running Shoes              41285.25
Wireless Headphones        33877.40
Dumbbell Set               30184.90
Mechanical Keyboard        26489.40
Electric Kettle            26382.40
Mixer Grinder              25341.55
Smart Watch                15670.25
Yoga Mat                   12765.80
Atomic Habits              11590.65
Football                   10307.10
Water Bottle                9995.70
Wireless Mouse              9574.35
T-Shirt                     7790.25
Hoodie                      7675.20
Python Programming          7527.45
The Alchemist               7485.00
Power Bank                  6474.60
Jeans                       6456.60
Machine Learning Basics     5694.30
Data Science Handbook       4495.00
Name: Total_Sales, dtype: float64

In [25]:
product_sales.head(10)

Product
Coffee Maker           51610.25
Jacket                 47106.15
Cricket Bat            41483.40
Running Shoes          41285.25
Wireless Headphones    33877.40
Dumbbell Set           30184.90
Mechanical Keyboard    26489.40
Electric Kettle        26382.40
Mixer Grinder          25341.55
Smart Watch            15670.25
Name: Total_Sales, dtype: float64

In [26]:
payment_sales = (
    df.groupby("Payment_Method")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

payment_sales

Payment_Method
Credit Card         106540.25
Debit Card           98064.90
Net Banking          96371.25
UPI                  96163.25
Cash on Delivery     50123.30
Name: Total_Sales, dtype: float64

In [27]:
payment_analysis = df.groupby("Payment_Method").agg(
    Total_Sales=("Total_Sales", "sum"),
    Average_Sales=("Total_Sales", "mean"),
    Total_Quantity=("Quantity", "sum"),
    Number_of_Orders=("Order_ID", "count")
).sort_values("Total_Sales", ascending=False)

payment_analysis

                  Total_Sales  Average_Sales  Total_Quantity  Number_of_Orders
Payment_Method
Credit Card         106540.25    4842.738636              65                22
Debit Card           98064.90    4903.245000              64                20
Net Banking          96371.25    5668.897059              63                17
UPI                  96163.25    3698.586538              70                26
Cash on Delivery     50123.30    3341.553333              32                15

In [28]:
above_average = df[df["Total_Sales"] > df["Total_Sales"].mean()]

above_average

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
7,1008,2026-04-27,Aman Kumar,Jammu,North,Clothing,Hoodie,4,1599,5,6076.20,4.3,Credit Card
8,1009,2026-06-05,Aman Kumar,Mumbai,West,Home & Kitchen,Electric Kettle,3,1499,0,4497.00,4.0,Cash on Delivery
9,1010,2026-03-11,Aman Kumar,Kochi,South,Clothing,Jacket,4,2499,10,8996.40,4.7,Credit Card
10,1011,2026-03-22,Rahul Das,Hyderabad,South,Home & Kitchen,Coffee Maker,2,3499,0,6998.00,4.2,UPI
11,1012,2026-04-12,Aman Kumar,Chandigarh,North,Sports,Cricket Bat,2,2499,10,4498.20,4.6,Credit Card
12,1013,2026-03-09,Maryam Khan,Lucknow,North,Clothing,Jacket,5,2499,15,10620.75,4.8,Net Banking
13,1014,2026-02-05,Dev Patel,Jaipur,North,Sports,Running Shoes,3,2799,0,8397.00,4.6,UPI
16,1017,2026-03-17,Sana Malik,Hyderabad,South,Sports,Cricket Bat,3,2499,0,7497.00,4.0,Net Banking
18,1019,2026-05-19,Reyansh Jain,Chennai,South,Clothing,Jacket,3,2499,0,7497.00,4.7,UPI
25,1026,2026-05-12,Sara Ahmed,Chandigarh,North,Electronics,Wireless Headphones,3,1499,0,4497.00,4.2,Net Banking
27,1028,2026-04-19,Sana Malik,Chandigarh,North,Electronics,Wireless Headphones,4,1499,5,5696.20,4.6,UPI
28,1029,2026-01-28,Sara Ahmed,Hyderabad,South,Electronics,Wireless Headphones,4,1499,5,5696.20,4.1,Credit Card
32,1033,2026-06-28,Maryam Khan,Pune,West,Home & Kitchen,Mixer Grinder,3,2999,10,8097.30,4.7,Net Banking
37,1038,2026-03-08,Aditya Verma,Pune,West,Sports,Dumbbell Set,5,1999,5,9495.25,5.0,Debit Card
38,1039,2026-04-28,Vivaan Kapoor,Chandigarh,North,Home & Kitchen,Mixer Grinder,2,2999,5,5698.10,3.8,UPI
40,1041,2026-03-14,Ishita Gupta,Delhi,North,Home & Kitchen,Coffee Maker,2,3499,5,6648.10,4.6,Cash on Delivery
47,1048,2026-06-24,Sara Ahmed,Lucknow,North,Home & Kitchen,Coffee Maker,3,3499,0,10497.00,5.0,UPI
48,1049,2026-03-02,Ishita Gupta,Mumbai,West,Sports,Running Shoes,5,2799,0,13995.00,4.0,Net Banking
50,1051,2026-04-28,Aisha Mir,Bhubaneswar,East,Electronics,Smart Watch,2,3299,0,6598.00,4.2,Credit Card
51,1052,2026-03-13,Rohan Mehta,Chandigarh,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.2,Debit Card
52,1053,2026-01-08,Ananya Singh,Hyderabad,South,Sports,Running Shoes,5,2799,5,13295.25,4.2,Credit Card
56,1057,2026-03-21,Alina Shah,Chennai,South,Home & Kitchen,Coffee Maker,3,3499,15,8922.45,4.5,Debit Card
58,1059,2026-01-01,Mehak Bhat,Chennai,South,Sports,Cricket Bat,4,2499,15,8496.60,4.2,Credit Card
59,1060,2026-04-24,Karan Joshi,Pune,West,Sports,Dumbbell Set,3,1999,10,5397.30,5.0,Credit Card
61,1062,2026-02-20,Kabir Ali,Mumbai,West,Electronics,Mechanical Keyboard,3,2499,0,7497.00,3.5,UPI
65,1066,2026-06-20,Dev Patel,Jaipur,North,Electronics,Smart Watch,2,3299,10,5938.20,4.7,Cash on Delivery
69,1070,2026-06-30,Aditya Verma,Delhi,North,Clothing,Jacket,4,2499,0,9996.00,3.8,Net Banking
75,1076,2026-04-29,Ishita Gupta,Chennai,South,Electronics,Wireless Headphones,4,1499,0,5996.00,3.5,Debit Card
76,1077,2026-03-28,Reyansh Jain,Pune,West,Home & Kitchen,Electric Kettle,4,1499,5,5696.20,4.5,Debit Card
79,1080,2026-05-25,Aditya Verma,Delhi,North,Clothing,Jacket,4,2499,0,9996.00,4.6,Debit Card
80,1081,2026-01-30,Reyansh Jain,Kolkata,East,Home & Kitchen,Electric Kettle,5,1499,15,6370.75,4.0,Debit Card
84,1085,2026-01-28,Sana Malik,Hyderabad,South,Home & Kitchen,Coffee Maker,4,3499,10,12596.40,4.3,Net Banking
89,1090,2026-05-13,Aditya Verma,Lucknow,North,Sports,Cricket Bat,5,2499,0,12495.00,3.8,Credit Card
91,1092,2026-04-14,Nikhil Sood,Ahmedabad,West,Electronics,Wireless Headphones,3,1499,0,4497.00,4.1,Debit Card
92,1093,2026-05-16,Aisha Mir,Hyderabad,South,Sports,Cricket Bat,4,2499,15,8496.60,4.5,Cash on Delivery
93,1094,2026-03-06,Sara Ahmed,Mumbai,West,Home & Kitchen,Mixer Grinder,3,2999,5,8547.15,3.8,Credit Card
95,1096,2026-01-26,Aditya Verma,Kochi,South,Sports,Dumbbell Set,5,1999,5,9495.25,4.2,Credit Card
97,1098,2026-01-04,Yusuf Dar,Bengaluru,South,Home & Kitchen,Electric Kettle,4,1499,0,5996.00,4.2,Net Banking
99,1100,2026-02-08,Kabir Ali,Pune,West,Books,Data Science Handbook,5,899,0,4495.00,4.8,Debit Card

In [30]:
summary = pd.Series({
    "Total Sales": df["Total_Sales"].sum(),
    "Average Sales": df["Total_Sales"].mean(),
    "Highest Sale": df["Total_Sales"].max(),
    "Lowest Sale": df["Total_Sales"].min(),
    "Total Quantity Sold": df["Quantity"].sum(),
    "Number of Orders": df["Order_ID"].nunique(),
    "Average Rating": df["Rating"].mean()
})

summary

Total Sales            447262.9500
Average Sales            4472.6295
Highest Sale            13995.0000
Lowest Sale               449.1000
Total Quantity Sold       294.0000
Number of Orders          100.0000
Average Rating              4.3220
dtype: float64